### ISSUE TITLE
ERROR IN README... 

### ISSUE THREAD

**Issue by ManuelBot59** [rlyonheart/osinteye#1]
Hello, error mentioning url in README.md

ERROR............................................................................
Clone project:
git clone https:/github.com/rlyonheart/osinteye.git

CORRECT............................................................................
Clone project:
git clone https://github.com/rlyonheart/osinteye.git

**Comment by rly0nheart** [comment]
Hey thanks a lot!, I will correct that mistake as soon as possible 🙂
